source 'https://github.com/CocoaPods/Specs.git'
 
 platform :ios, ’11.0’
 use_frameworks!
 
 target :’EmployeeApp' do
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSSQS'
 end

